sources:
  - robomatn.ufo

familyName: "RoboMatn"

buildVariable: false
buildStatic: true
buildTTF: true
buildOTF: false
buildSmallCap: false

# Disable overlap removal – it fails on qcurve glyphs
removeOutlineOverlaps: false
